export const ActionTypes = {
  POKEMON_LIST: "POKEMON_LIST",
  SET_POKEMON_LIST: "SET_POKEMON_LIST",

  DETAIL_POKEMON: "DETAIL_POKEMON",
  SET_DETAIL_POKEMON: "SET_DETAIL_POKEMON",

  PROBABILITY: "PROBABILITY",
  SET_PROBABILITY: "SET_PROBABILITY",

  CATCH_POKEMON: "CATCH_POKEMON",
  SET_CATCH_POKEMON: "SET_CATCH_POKEMON",

  MY_POKEMON: "MY_POKEMON",
  SET_MY_POKEMON: "SET_MY_POKEMON",

  RENAME_POKEMON: "RENAME_POKEMON",
  SET_RENAME_POKEMON: "SET_RENAME_POKEMON",

  CHECK_PRIME: "CHECK_PRIME",

  SET_RELEASE: "SET_RELEASE",

  ERROR: "ERROR",
};
